from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="korean-sllm",
    version="0.1.0",
    author="Your Name",
    author_email="your.email@example.com",
    description="Korean small Language Model implemented from scratch with PyTorch",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/korean-sllm",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Text Processing :: Linguistic",
    ],
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "torchaudio>=2.0.0",
        "transformers>=4.30.0",
        "datasets>=2.10.0",
        "tokenizers>=0.13.0",
        "accelerate>=0.20.0",
        "safetensors>=0.3.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "tqdm>=4.60.0",
        "wandb>=0.15.0",
        "regex>=2022.1.18",
        "requests>=2.28.0",
        "pyyaml>=6.0",
        "psutil>=5.8.0",
        "pillow>=8.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0",
            "pytest-cov>=2.0",
            "black>=22.0",
            "flake8>=4.0",
            "isort>=5.0",
            "mypy>=0.950",
        ],
        "docs": [
            "sphinx>=4.0",
            "sphinx-rtd-theme>=1.0",
            "myst-parser>=0.17",
        ],
    },
    entry_points={
        "console_scripts": [
            "korean-sllm-train=korean_sllm.training:main",
            "korean-sllm-infer=korean_sllm.inference:main",
            "korean-sllm-validate=korean_sllm.validation:main",
        ],
    },
    include_package_data=True,
    zip_safe=False,
) 